version: '2'
services:
  dev:
    image: vuedev:v1
    container_name: vue_cli3_demo
    ports:
     - "8080:8080"
    restart: always
    volumes: 
     - ./:/workspace
    stdin_open: true
    tty: true